import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

export const theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#3B82F6',
    primaryContainer: '#DBEAFE',
    secondary: '#8B5CF6',
    secondaryContainer: '#EDE9FE',
    tertiary: '#10B981',
    tertiaryContainer: '#D1FAE5',
    error: '#EF4444',
    errorContainer: '#FEE2E2',
    background: '#FFFFFF',
    surface: '#FFFFFF',
    surfaceVariant: '#F8FAFC',
    outline: '#E2E8F0',
    outlineVariant: '#CBD5E1',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#1E3A8A',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#4C1D95',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#065F46',
    onError: '#FFFFFF',
    onErrorContainer: '#991B1B',
    onBackground: '#0F172A',
    onSurface: '#0F172A',
    onSurfaceVariant: '#475569',
    onOutline: '#64748B',
    onOutlineVariant: '#94A3B8',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#1E293B',
    inverseOnSurface: '#F1F5F9',
    inversePrimary: '#93C5FD',
    elevation: {
      level0: 'transparent',
      level1: '#FFFFFF',
      level2: '#FFFFFF',
      level3: '#FFFFFF',
      level4: '#FFFFFF',
      level5: '#FFFFFF',
    },
    surfaceDisabled: '#F1F5F9',
    onSurfaceDisabled: '#94A3B8',
    backdrop: 'rgba(0, 0, 0, 0.5)',
  },
  fonts: {
    ...MD3LightTheme.fonts,
    displayLarge: {
      fontFamily: 'Inter-Bold',
      fontSize: 57,
      lineHeight: 64,
      letterSpacing: -0.25,
    },
    displayMedium: {
      fontFamily: 'Inter-Bold',
      fontSize: 45,
      lineHeight: 52,
      letterSpacing: 0,
    },
    displaySmall: {
      fontFamily: 'Inter-Bold',
      fontSize: 36,
      lineHeight: 44,
      letterSpacing: 0,
    },
    headlineLarge: {
      fontFamily: 'Inter-Bold',
      fontSize: 32,
      lineHeight: 40,
      letterSpacing: 0,
    },
    headlineMedium: {
      fontFamily: 'Inter-Bold',
      fontSize: 28,
      lineHeight: 36,
      letterSpacing: 0,
    },
    headlineSmall: {
      fontFamily: 'Inter-Bold',
      fontSize: 24,
      lineHeight: 32,
      letterSpacing: 0,
    },
    titleLarge: {
      fontFamily: 'Inter-SemiBold',
      fontSize: 22,
      lineHeight: 28,
      letterSpacing: 0,
    },
    titleMedium: {
      fontFamily: 'Inter-SemiBold',
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.15,
    },
    titleSmall: {
      fontFamily: 'Inter-SemiBold',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
    },
    bodyLarge: {
      fontFamily: 'Inter-Regular',
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.5,
    },
    bodyMedium: {
      fontFamily: 'Inter-Regular',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.25,
    },
    bodySmall: {
      fontFamily: 'Inter-Regular',
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.4,
    },
    labelLarge: {
      fontFamily: 'Inter-Medium',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
    },
    labelMedium: {
      fontFamily: 'Inter-Medium',
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.5,
    },
    labelSmall: {
      fontFamily: 'Inter-Medium',
      fontSize: 11,
      lineHeight: 16,
      letterSpacing: 0.5,
    },
  },
  roundness: 12,
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#60A5FA',
    primaryContainer: '#1E3A8A',
    secondary: '#A78BFA',
    secondaryContainer: '#4C1D95',
    tertiary: '#34D399',
    tertiaryContainer: '#065F46',
    error: '#F87171',
    errorContainer: '#991B1B',
    background: '#0F172A',
    surface: '#1E293B',
    surfaceVariant: '#334155',
    outline: '#475569',
    outlineVariant: '#64748B',
    onPrimary: '#0F172A',
    onPrimaryContainer: '#DBEAFE',
    onSecondary: '#0F172A',
    onSecondaryContainer: '#EDE9FE',
    onTertiary: '#0F172A',
    onTertiaryContainer: '#D1FAE5',
    onError: '#0F172A',
    onErrorContainer: '#FEE2E2',
    onBackground: '#F8FAFC',
    onSurface: '#F8FAFC',
    onSurfaceVariant: '#CBD5E1',
    onOutline: '#94A3B8',
    onOutlineVariant: '#CBD5E1',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#F1F5F9',
    inverseOnSurface: '#1E293B',
    inversePrimary: '#1E3A8A',
    elevation: {
      level0: 'transparent',
      level1: '#1E293B',
      level2: '#334155',
      level3: '#475569',
      level4: '#64748B',
      level5: '#94A3B8',
    },
    surfaceDisabled: '#334155',
    onSurfaceDisabled: '#64748B',
    backdrop: 'rgba(0, 0, 0, 0.5)',
  },
  fonts: theme.fonts,
  roundness: 12,
}; 